services:
    K3ssen\SymfonyVueBundle\Vue\VueDataStorage:
        autoconfigure: true

    K3ssen\SymfonyVueBundle\Vue\VueExtension:
        autoconfigure: true
        arguments:
            $vueDataStorage: '@K3ssen\SymfonyVueBundle\Vue\VueDataStorage'
