services:
    _defaults:
        autowire: true
        autoconfigure: true

    K3ssen\SymfonyVuetified\Vue\VueDataStorage:
        autoconfigure: true

    K3ssen\SymfonyVuetified\Vue\VueExtension:
        $vueDataStorage: '@K3ssen\SymfonyVuetified\Vue\VueDataStorage'

    K3ssen\SymfonyVuetified\Form\:
        resource: '../../Form/*'