example_index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: example/index.vue.twig

example_fetch:
    path: /fetch
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: example/fetch.vue.twig

example_form:
    path: /form
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: example/form.vue.twig
