services:
    _defaults:
        autowire: true
        autoconfigure: true

# You can remove the code below - it's just an example.
twig:
    globals:
        exampleForm: '@App\Form\ExampleType'

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: ~
                driver:   pdo_sqlite
                path:     '%kernel.cache_dir%/test.db'
